name: Setup asdf
description: Install tools versioned with asdf
author: Victor Borja <vborja@apache.org>
runs:
  using: node20
  main: main.js
inputs:
  asdf_branch:
    description: asdf branch to clone
    required: false
    default: 31e8c93004abd76253d186b8896785895069749b
  skip_install:
    description: setup env without installing asdf
    required: false
    default: false
